### ISSUE TITLE
Error while compiling.

### ISSUE THREAD

**Issue by zsy-v** [resetius/miniraft-cpp#5]
Hello, thank you for your work on raft. I'm currently facing some issues while compiling. Can you help me?

zhousy26@zhousy26-virtual-machine:~/Desktop/testc/miniraft-cpp$ make
Consolidate compiler generated dependencies of target coroio
[  2%] Building CXX object coroio/CMakeFiles/coroio.dir/coroio/uring.cpp.o
[  5%] Building CXX object coroio/CMakeFiles/coroio.dir/coroio/resolver.cpp.o
[  7%] Linking CXX static library libcoroio.a
[ 25%] Built target coroio
Consolidate compiler generated dependencies of target miniraft
[ 27%] Building CXX object CMakeFiles/miniraft.dir/src/server.cpp.o
[ 30%] Linking CXX static library libminiraft.a
[ 35%] Built target miniraft
Consolidate compiler generated dependencies of target test_raft
[ 37%] Building CXX object CMakeFiles/test_raft.dir/test/test_raft.cpp.o
[ 40%] Linking CXX executable test_raft
[ 40%] Built target test_raft
Consolidate compiler generated dependencies of target test_read_write
[ 42%] Building CXX object CMakeFiles/test_read_write.dir/test/test_read_write.cpp.o
[ 45%] Linking CXX executable test_read_write
/usr/bin/ld: coroio/libcoroio.a(uring.cpp.o): in function `NNet::TUring::TUring(int)':
uring.cpp:(.text+0x459): undefined reference to `io_uring_queue_init'
/usr/bin/ld: coroio/libcoroio.a(uring.cpp.o): in function `NNet::TUring::~TUring()':
uring.cpp:(.text+0x758): undefined reference to `io_uring_queue_exit'
/usr/bin/ld: coroio/libcoroio.a(uring.cpp.o): in function `NNet::TUring::Wait(timespec)':
uring.cpp:(.text+0xb92): undefined reference to `io_uring_wait_cqe_timeout'
/usr/bin/ld: coroio/libcoroio.a(uring.cpp.o): in function `NNet::TUring::Submit()':
uring.cpp:(.text+0xde9): undefined reference to `io_uring_submit'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test_read_write.dir/build.make:99: test_read_write] Error 1
make[1]: *** [CMakeFiles/Makefile2:180: CMakeFiles/test_read_write.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

**Comment by resetius** [comment]
Hello, could you pls give me output of `lsb_release -a` and `make VERBOSE=1` ? Thank you.

**Comment by zsy-v** [comment]
I may have just resolved the issue. Simply linking liburing.so in the CMakeLists.txt using target_link_libraries seems to have resolved the definition problem. The compilation has now completed. The executable file has produced the following output. Would this program run correctly? As a computer science student, I'm looking to understand the principles of Raft through this project.

server1:
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 
Leader, Term: 14, Index: 0, CommitIndex: 0, Delay: 2:0 3:0 MatchIndex: 2:0 3:0 NextIndex: 2:1 3:1 

server2:
Follower, Term: 14, Index: 0, CommitIndex: 0, 
Follower, Term: 14, Index: 0, CommitIndex: 0, 
Follower, Term: 14, Index: 0, CommitIndex: 0, 
Follower, Term: 14, Index: 0, CommitIndex: 0, 
Follower, Term: 14, Index: 0, CommitIndex: 0, 
Follower, Term: 14, Index: 0, CommitIndex: 0, 
Follower, Term: 14, Index: 0, CommitIndex: 0, 
Follower, Term: 14, Index: 0, CommitIndex: 0, 
Follower, Term: 14, Index: 0, CommitIndex: 0, 

server3:
Follower, Term: 14, Index: 0, CommitIndex: 0, 
Follower, Term: 14, Index: 0, CommitIndex: 0, 
Follower, Term: 14, Index: 0, CommitIndex: 0, 
Follower, Term: 14, Index: 0, CommitIndex: 0, 

client:
/client_exe --node 127.0.0.1:8001:1
Connected

**Comment by resetius** [comment]
Correct. Try to send smth with `client`. You will see incrementing indices.

**Comment by sinashan** [comment]
could you clarify how exactly did you add liburing.so to target_link_libraries? I'm getting the same error

**Comment by zsy-v** [comment]
1111

**Comment by sinashan** [comment]
????

**Comment by resetius** [comment]
> could you clarify how exactly did you add liburing.so to target_link_libraries? I'm getting the same error

I use `public` dependency inside coroio/CMakeLists.txt: `target_link_libraries(coroio PUBLIC ${URING_LIBRARIES} ${OPENSSL_LIBRARIES})`. As a result when I set dependency on `coroio` a dependency on `uring` is also set.

**Comment by resetius** [comment]
> it seems that's already set in CMakeList for coroio but i'm still facing the problem

What OS do you use?

**Comment by sinashan** [comment]
i'm using Ubuntu 22.04.4 LTS

**Comment by resetius** [comment]
Ok. I'll try to reproduce today.

**Comment by zsy-v** [comment]
I apologize for the accidental and irrelevant response. I am also using an Ubuntu system with an image of ubuntu-23.04-desktop-amd64.iso. I recall adding an option **-option** during compilation to utilize certain libraries, but currently, I can't access to that machine and have forgotten what the specific **option** was.

**Comment by resetius** [comment]
pls do `git pull ` and `git submodule update`
Fixed in https://github.com/resetius/coroio/commit/e333bbad992a8243acc1882364271b86985f365d
